SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM
    FOOD_PRODUCT P
JOIN (
    SELECT *
    FROM FOOD_ORDER
    WHERE PRODUCE_DATE LIKE "2022-05%"
) AS O
ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY
    TOTAL_SALES DESC,
    P.PRODUCT_ID ASC