SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN (
    SELECT CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
) AS S
ON D.SKILL_CODE & S.CODE != 0
ORDER BY D.ID