WITH SEDAN AS(
    SELECT DISTINCT H.CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '세단'
    AND (H.START_DATE BETWEEN '2022-10-01' AND '2022-10-31')
)

SELECT *
FROM SEDAN
ORDER BY CAR_ID DESC