WITH FOOD AS(
    SELECT CATEGORY AS C, MAX(PRICE) AS M
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)

SELECT F.C, F.M, P.PRODUCT_NAME
FROM FOOD F
JOIN FOOD_PRODUCT AS P
ON F.M = P.PRICE AND F.C = P.CATEGORY
ORDER BY F.M DESC