WITH PERIOD AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= '2022-08-01'
    AND START_DATE < '2022-11-01'
),
CARS AS (
    SELECT CAR_ID
    FROM PERIOD
    GROUP BY CAR_ID
    HAVING COUNT(*) > 4
)

SELECT MONTH(P.START_DATE), P.CAR_ID, COUNT(*) AS RECORDS
FROM PERIOD P
JOIN CARS C
ON P.CAR_ID = C.CAR_ID
GROUP BY MONTH(P.START_DATE), P.CAR_ID
ORDER BY MONTH(P.START_DATE) ASC, P.CAR_ID DESC