WITH USER AS(
    SELECT USER_ID AS UID, GENDER
    FROM USER_INFO
    WHERE GENDER IS NOT NULL
)

SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER, COUNT(DISTINCT(UID)) AS USERS
FROM ONLINE_SALE O
JOIN USER U
ON O.USER_ID = U.UID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE), GENDER
ORDER BY YEAR(SALES_DATE) ASC, MONTH(SALES_DATE) ASC, GENDER ASC