WITH RECURSIVE TIME AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM TIME
    WHERE HOUR<23
), CTE AS(
    SELECT HOUR(DATETIME) AS H, COUNT(DISTINCT(ANIMAL_ID)) AS CNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR(DATETIME)
)

SELECT T.HOUR, IFNULL(CNT, 0) AS COUNT
FROM TIME T
LEFT JOIN CTE C
ON T.HOUR = C.H