WITH M AS(
    SELECT YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS S
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
), CTE AS(
    SELECT M.Y AS YEAR, (M.S - E.SIZE_OF_COLONY) AS YEAR_DEV, E.ID
    FROM ECOLI_DATA E
    JOIN M
    ON YEAR(E.DIFFERENTIATION_DATE) = M.Y
)

SELECT *
FROM CTE
ORDER BY YEAR ASC, YEAR_DEV ASC