SELECT
    P.PRODUCT_CODE,
    (O.CNT * P.PRICE) AS SALES
FROM (
    SELECT
        PRODUCT_ID,
        SUM(SALES_AMOUNT) AS CNT
    FROM
        OFFLINE_SALE
    GROUP BY
        PRODUCT_ID
) AS O
JOIN
    PRODUCT P
ON
    O.PRODUCT_ID = P.PRODUCT_ID
ORDER BY 
    SALES DESC,
    P.PRODUCT_CODE ASC
    