WITH MAIN AS(
    SELECT WRITER_ID AS ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) >= 3
)

SELECT U.USER_ID, U.NICKNAME, CONCAT_WS(' ', U.CITY, U.STREET_ADDRESS1, U.STREET_ADDRESS2) AS 전체주소, CONCAT_WS('-', SUBSTR(U.TLNO,1,3), SUBSTR(U.TLNO,4,4), SUBSTR(U.TLNO,8,4)) AS 전화번호
FROM USED_GOODS_USER U
JOIN MAIN M
ON U.USER_ID = M.ID
ORDER BY U.USER_ID DESC