WITH TOTAL AS(
    SELECT COUNT(*) AS CNT
    FROM USER_INFO
    WHERE JOINED LIKE "2021%"
)

SELECT
    YEAR(O.SALES_DATE) AS YEAR, 
    MONTH(O.SALES_DATE) AS MONTH,
    COUNT(DISTINCT o.user_id) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT o.user_id) / U.CNT, 1) AS PUCHASED_RATIO
FROM (
    SELECT *
    FROM USER_INFO
    JOIN TOTAL
    WHERE JOINED LIKE "2021%"
) AS U
JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
GROUP BY DATE_FORMAT(O.SALES_DATE, "%Y"), DATE_FORMAT(O.SALES_DATE, "%m")
ORDER BY 
    DATE_FORMAT(O.SALES_DATE, "%Y") ASC,
    DATE_FORMAT(O.SALES_DATE, "%m") ASC