WITH RECURSIVE ECOLI_GENERATION AS (
    SELECT 
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM 
        ECOLI_DATA
    WHERE 
        PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT 
        E.ID,
        E.PARENT_ID,
        EG.GENERATION + 1
    FROM 
        ECOLI_DATA AS E
    JOIN 
        ECOLI_GENERATION AS EG 
    ON 
        EG.ID = E.PARENT_ID
)

SELECT 
    COUNT(*) AS COUNT,
    P.GENERATION
FROM
    ECOLI_GENERATION AS P
LEFT JOIN
    ECOLI_GENERATION AS C
ON
    P.ID = C.PARENT_ID
WHERE
    C.ID IS NULL
GROUP BY
    P.GENERATION
ORDER BY
    P.GENERATION