WITH BOOKSALES AS(
    SELECT BOOK.BOOK_ID, SUM(SALES) * BOOK.PRICE AS S
    FROM BOOK_SALES
    JOIN BOOK
    ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
)

SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.S) AS TOTAL_SALES
FROM BOOKSALES S
JOIN BOOK B
ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR A
ON B.AUTHOR_ID = A.AUTHOR_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC