WITH MOST AS(
    SELECT MAX(VIEWS) AS VIEW
    FROM USED_GOODS_BOARD
), MOST_ID AS(
    SELECT BOARD_ID AS ID
    FROM USED_GOODS_BOARD U
    JOIN MOST M
    ON U.VIEWS = M.VIEW
), CTE AS(
    SELECT *
    FROM USED_GOODS_FILE U
    JOIN MOST_ID M
    ON U.BOARD_ID = M.ID
)


SELECT CONCAT("/home/grep/src/", ID, "/", FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM CTE
ORDER BY FILE_ID DESC