WITH CS AS(
    SELECT *
    FROM APPOINTMENT
    WHERE MCDP_CD = 'CS'
    AND APNT_YMD LIKE '2022-04-13%'
    AND APNT_CNCL_YN = 'N'
)

SELECT C.APNT_NO, P.PT_NAME, C.PT_NO, C.MCDP_CD, D.DR_NAME, C.APNT_YMD
FROM CS C
JOIN PATIENT P
ON C.PT_NO = P.PT_NO
JOIN DOCTOR D
ON C.MDDR_ID = D.DR_ID
ORDER BY C.APNT_YMD