# WITH B AS(
#     SELECT *
#     FROM USED_GOODS_BOARD B
#     WHERE B.CREATED_DATE LIKE '2022-10%'
# )

# SELECT *
# FROM B

SELECT DISTINCT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS,
DATE_FORMAT(R.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R
ON B.board_id = R.board_id
WHERE B.CREATED_DATE LIKE '2022-10%'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;