WITH TRUCK AS(
    SELECT H.HISTORY_ID, H.CAR_ID, C.DAILY_FEE, C.OPTIONS, DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DAY,
        CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 90 THEN "90일 이상"
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 30 THEN "30일 이상"
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) >= 7 THEN "7일 이상"
            ELSE "없음"
        END AS GAP
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
), TRUCK_DIS AS(
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
), CTE AS(
    SELECT T.HISTORY_ID, T.DAILY_FEE, T.DAY, IFNULL(D.DISCOUNT_RATE, 0) AS RATE
    FROM TRUCK T
    LEFT JOIN TRUCK_DIS D
    ON T.GAP = D.DURATION_TYPE
)

SELECT HISTORY_ID, TRUNCATE(DAILY_FEE*(100-RATE)/100*DAY, 0) AS FEE
FROM CTE
ORDER BY TRUNCATE(DAILY_FEE*(100-RATE)/100*DAY, 0) DESC, HISTORY_ID DESC