WITH SCODE AS(
    SELECT
        (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY = 'Front End') AS F,
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') AS P,
        (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') AS C
),
CTE AS(
    SELECT
        CASE
            WHEN (S.F & D.SKILL_CODE) <> 0 AND (S.P & D.SKILL_CODE) = S.P THEN 'A'
            WHEN (S.C & D.SKILL_CODE) = S.C THEN 'B'
            WHEN (S.F & D.SKILL_CODE) <> 0 THEN 'C'
        END AS GRADE,
    D.ID,
    D.EMAIL
    FROM DEVELOPERS D
    CROSS JOIN SCODE S
)

SELECT
    GRADE,
    ID,
    EMAIL
FROM CTE
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID ASC