WITH ID AS (
    SELECT BOOK_ID AS BID, SUM(SALES) AS SALE
    FROM BOOK_SALES
    WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
    GROUP BY BOOK_ID
), MAIN AS (
    SELECT *
    FROM ID
    JOIN BOOK B
    ON ID.BID = B.BOOK_ID
)

SELECT CATEGORY, SUM(SALE) AS TOTAL_SALES
FROM MAIN
GROUP BY CATEGORY
ORDER BY CATEGORY ASC