WITH TOP_REST AS(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS F
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT T.FOOD_TYPE, I.REST_ID, I.REST_NAME, T.F
FROM TOP_REST T
JOIN REST_INFO I
ON T.FOOD_TYPE = I.FOOD_TYPE
AND T.F = I.FAVORITES
ORDER BY T.FOOD_TYPE DESC