WITH GR AS(
    SELECT FISH_TYPE AS TP, MAX(LENGTH) AS LEN
    FROM FISH_INFO
    GROUP BY FISH_TYPE
), FISH AS(
    SELECT F.ID, F.FISH_TYPE, F.LENGTH, N.FISH_NAME
    FROM FISH_INFO F
    JOIN FISH_NAME_INFO N
    ON F.FISH_TYPE = N.FISH_TYPE
), MAIN AS(
    SELECT F.ID, F.FISH_NAME, G.LEN AS LENGTH
    FROM FISH F
    JOIN GR G
    ON F.FISH_TYPE = G.TP
    AND F.LENGTH = G.LEN
    ORDER BY F.ID
)

SELECT *
FROM MAIN