WITH COMP AS (
    SELECT WRITER_ID AS W, SUM(PRICE) AS P 
    FROM USED_GOODS_BOARD
    WHERE STATUS = 'DONE'
    GROUP BY WRITER_ID
)

SELECT U.USER_ID, U.NICKNAME, C.P AS TOTAL_SALES
FROM COMP C
JOIN USED_GOODS_USER U
ON C.W = U.USER_ID
WHERE C.P >= 700000
ORDER BY C.P ASC