SELECT AAA.ID
FROM ECOLI_DATA AAA
WHERE AAA.PARENT_ID
IN(
    SELECT ID
    FROM ECOLI_DATA AS AA
    WHERE AA.PARENT_ID 
    IN (
        SELECT A.ID
        FROM ECOLI_DATA AS A
        WHERE PARENT_ID IS NULL
    )
)
ORDER BY AAA.ID ASC